### ISSUE TITLE
I have two koa API boilerplates you should add.

### ISSUE THREAD

**Issue by maotora** [ellerbrock/awesome-koa#10]
Hi,

I love Koa and I made 2 contributions API boilerplate contributions that I would like to be added on the list.

[koa user-api](https://github.com/maotora/koa-userapi)

and

[koa blog-api](https://github.com/maotora/koa-blogapi)

they both pass tests, need more users & contributions & most of all use koa v2 and other useful koa-middlewares like 
[koa-rest-router](https://https://github.com/tunnckoCore/koa-rest-router).

Thanks.

**Comment by ellerbrock** [comment]
Hi @maotora,

can you please make a PR with your boilerplates?

Thanks

**Comment by maotora** [comment]
Hello @ellerbrock ,

Thank you for the response.
I've made the pull request.
